<?php 
if($this->_action=='admin')
{
    echo $this->_Value;
}
else
{
    ?>
<textarea class="ckeditor" id="<?php echo $this->_idName;?>" name="<?php echo $this->_idName;?>" rows="6" ><?php echo $this->_Value; ?></textarea>
<?php
}
?>
<script src="https://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('<?php echo $this->_idName;?>');    
    
    require(['config'], function () {
    require(["jquery"],function($){
        timer = setInterval(updateDiv,100);
        function updateDiv(){
            var editorText = CKEDITOR.instances.<?php echo $this->_idName;?>.getData();
            $('#<?php echo $this->_idName;?>').html(editorText);
        }
      });
    }); 
    </script>