<?php
global $currentNode;
global $currentAction;
if($currentNode=='core_users' && $currentAction=='login')
{

}
else
{
?></div>
</div>
<?php
    $wp=new Core_WebsiteSettings();
?>

<footer id="footer" class="main-footer">
	<div class="span pull-right ">
         <span class="go-top scrollToTop "><i class="icon-arrow-up"></i></span>
      </div>
        <div class="pull-right hidden-xs">
          <b>Version</b> 1.0
        </div>
        <strong>Copyright © 2015-2016 <a href="http://weblozix.com">Weblozix</a>.</strong> All rights reserved.
</footer>

<!-- <div id="footer" class="main-footer">
    <span style="color: blue;font-weight: bolder;background: white; padding-right: 10px;"> Powered by</span><span style="color: red;font-weight: bolder;background: white;">Easy info</span>
      <div class="span pull-right ">
         <span class="go-top scrollToTop "><i class="icon-arrow-up"></i></span>
      </div>
   </div> -->
   
   
   <!-- END FOOTER -->
</div>
   <!-- BEGIN JAVASCRIPTS -->    
   <!-- Load javascripts at bottom, this will reduce page load time -->
   <?php
            $this->setFooter();
            $this->addDefaultCss();
            $this->addContent("
                    ");
            
            $this->addDefaultJs();
            $this->renderLayout();
   ?>
   <script type="text/javascript" src="<?php echo $wp->websiteUrl; ?>assets/bootstrap/js/bootstrap.min.js"></script>
   <script type="text/javascript" src="<?php echo $wp->websiteUrl; ?>js/theme/jquery.blockui.js"></script>
   <script type="text/javascript" src="<?php echo $wp->websiteUrl; ?>js/theme/jquery-ui.js"></script>
   
   <!-- start this js is required -->
   <script type="text/javascript" src="<?php echo $wp->websiteUrl; ?>js/theme/scripts.js"></script>
   <script type="text/javascript" src="<?php echo $wp->websiteUrl; ?>js/project/functions.js"></script>
   <script type="text/javascript" src="<?php echo $wp->websiteUrl; ?>js/theme/functions.js"></script>
   <script type="text/javascript" src="<?php echo $wp->websiteUrl; ?>js/project/project.js"></script>
   <!-- end this js is required -->
   
<script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    
     <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
    <script src="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="<?php echo $wp->websiteUrl; ?>js/theam1/app.min.js"></script>
    
    
   <script>
      jQuery(document).ready(function() {       
         // initiate layout and plugins
         App.init();
      });
   </script>
   <!-- END JAVASCRIPTS -->   
  
</body>
<!-- END BODY -->
</html>
<?php
}
?>