<?php
$cc= new \CoreClass();
$session=$cc->getObject("\Core\Session");
$sessionData=$session->getSessionData();  
$lb=$cc->getObject("\Core\Model\Language"); 
global $rootObj;
$wp=$rootObj;
$cssRootPath=$wp->websiteUrl."css/".$wp->themeName."/";
$jsRootPath=$wp->websiteUrl."js/".$wp->themeName."/";
$jspath=$wp->websiteUrl."Var/".$wp->identity."/design/adminhtml/".$wp->themeName."/js/";
global $currentNode;
global $currentAction;
$csspath = $wp->websiteUrl . "Var/" . $wp->identity . "/design/adminhtml/".$wp->themeName."/css/";
$jspath = $wp->websiteUrl . "Var/" . $wp->identity . "/design/adminhtml/".$wp->themeName."/js/";
if($currentNode=='core_users' && $currentAction=='login')
{  
}
else
{
    ob_start();
?>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta content="width=device-width, initial-scale=1.0" name="viewport" />
<meta content="" name="description" />
<meta content="" name="author" />
<meta charset="utf-8">
<title><?php echo $controllerObj->getPageTitle(); ?></title>
<?php             
            $this->addDefaultCss();
            $this->addContent("");
            $this->addDefaultJs();
            $this->renderLayout();
        ?>

<link href="<?php echo $wp->websiteUrl; ?>assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" /> 
<link href="<?php echo $wp->websiteUrl; ?>assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="<?php echo $wp->websiteUrl; ?>css/theam1/css/AdminLTE.min.css">
<!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="<?php echo $wp->websiteUrl; ?>css/theam1/css/skins/_all-skins.min.css">
<!-- iCheck -->
<link rel="stylesheet" href="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/iCheck/flat/blue.css">
<!-- Morris chart -->
<link rel="stylesheet" href="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/morris/morris.css">
<!-- jvectormap -->
<link rel="stylesheet" href="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
<!-- Date Picker -->
<link rel="stylesheet" href="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/datepicker/datepicker3.css">
<!-- Daterange picker -->
<link rel="stylesheet" href="<?php echo $wp->websiteUrl; ?>css/theam1/plugins/daterangepicker/daterangepicker-bs3.css">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="<?php echo $wp->websiteUrl; ?>css/theam1/css/styles.css">
<link rel="stylesheet" href="<?php echo $wp->websiteUrl; ?>css/theam1/css/sidemenu.css">
<link rel="stylesheet" href="<?php echo $wp->websiteUrl; ?>css/project/project.css">
<link rel="stylesheet" href="<?php echo $cssRootPath; ?>styles.css">

<!-- END JAVASCRIPTS -->   
    <script data-main="<?php echo $jspath; ?>requirejs/config" src="<?php echo $jspath; ?>requirejs/require.js" ></script>
	<script data-main="<?php echo $jspath; ?>requirejs/config" src="<?php echo $jspath; ?>jquery.js" ></script>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<style>
input[type="checkbox"] {
    width: 17px;
	height:17px;
}

</style>
    <style type="text/css">
	  [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
	  display: none !important;
	}
	  </style>
<body class="fixed-top hold-transition skin-blue sidebar-mini">
<div class="wrapper">
<div id="dialogoverlay"></div>
<div id="dialogbox">
  <div style="   
    background: rgb(194, 228, 236);
    color: darkslateblue;
    font-family: monospace;
    font-size: larger;
    font-style: inherit;
    font-weight: bolder;">
    <div id="dialogboxhead"></div>
    <div id="dialogboxbody"></div>
    <div id="dialogboxfoot"></div>
  </div>
</div>
<!-- BEGIN HEADER -->
<input type="hidden" name="doc_root" id="doc_root" value="<?php echo $this->_websiteSettings->websiteUrl;  ?>">
<header id="header" class="main-header nav navbar-fixed-top"> <a class="logo" href="<?php echo $wp->websiteAdminUrl; ?>" style=" color: rgb(10, 14, 114); font-size: 16px; "> 
  <input type="hidden" name="sitehost" id="sitehost" value="<?php echo $wp->websiteUrl; ?>" />
  <input type="hidden" name="sitehosttemplatePath" id="sitehosttemplatePath" value="<?php echo \Core::getTempAdminThemeUrl()."templates/"; ?>" />
  <input type="hidden" name="sitehostadmin" id="sitehostadmin" value="<?php echo $wp->websiteAdminUrl; ?>" />
  <!-- mini logo for sidebar mini 50x50 pixels --> 
  <span class="logo-mini"><b>N</b>core</span> 
  <!-- logo for regular state and mobile devices --> 
  <span class="logo-lg"><b>New Core</b></span> </a> 
  
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation"> 
    <!-- Sidebar toggle button--> 
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"> <span class="sr-only"></span> </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu"> 
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
                <?php if($sessionData['user_id']>0)
                {
                    
                    ?>
                    <img src="<?php echo $this->_websiteSettings->projectRootUploadUrl.$sessionData['image'];?>" alt="">
                    <?php
                }
                else
                {?>
                    <img src="<?php echo $wp->websiteUrl."img/avatar_small.jpg";?>" alt="">
                   <?php
                }
                ?>
                <span class="hidden-xs"><?php echo Core::getValueFromArray($sessionData,'name'); ?></span> 
            </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header"> 
                <?php if($sessionData['user_id']>0)
                {
                    
                    ?>
                    <img src="<?php echo $this->_websiteSettings->projectRootUploadUrl.$sessionData['image'];?>" alt="">
                    <?php
                }
                else
                {?>
                    <img src="<?php echo $wp->websiteUrl."img/avatar_small.jpg";?>" alt="">
                   <?php
                }
                ?>
              <p> <?php echo Core::getValueFromArray($sessionData,'name'); ?> </p>
            </li>           
            <!-- Menu Footer-->
            <li class="user-footer">
                <?php
                if($sessionData['user_id']>0)
                {
                ?>
              <div class="pull-left"> <a href="<?php echo $wp->websiteAdminUrl."core_users/changepassword"; ?>" class="btn btn-default btn-flat">Change Password</a> </div>
                <?php } ?>
              <div class="pull-right"> <a href="<?php echo $wp->websiteAdminUrl."core_users/logout"; ?>" class="btn btn-default btn-flat"><i class="icon-key"></i> Log Out</a> </div>
            </li>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
        
      </ul>
    </div>
  </nav>
</header>
<aside class="main-sidebar">
    <section class="sidebar">
    <div ng-controller="menuTest" ng-cloak>
   <ul class="sidebar-menu" >
       <li class="treeview" ng-repeat="sideMenuItem in sideMenuItemList">
         <a href="javascript:;">
             <i class="{{sideMenuItem.classIcon}}"></i>
             <span>{{sideMenuItem.name}}</span></a>   
           <ul class="sidebar-submenu" ng-repeat="sidesubMenuItem in sideMenuItem.submenu">
            <li class="dropdown " name="link_core_backup" id="link_core_backup-core_backup">
               <a href="javascript:;">
                  <div><span class="{{sidesubMenuItem.classIcon}}">
                     </span>{{sidesubMenuItem.name}}
                  </div>
               </a>
               <ul class=" sidebar-submenu" ng-repeat="menulink in sidesubMenuItem.menulinks" >
                  <li><a href="{{menuBaseLink}}{{menulink.linkslug}}">{{menulink.linkanchortitle}}</a></li>                  
               </ul>
            </li>
         </ul>
      </li>
   </ul>
    </div>
</section>


</aside>
<span id="div_loading" class="loader1" style="display:none"> Data will be under processing </span> 
<!-- END HEADER -->
<div id="container" class="row-fluid">
<div class="row">

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Main content -->
<section class="content" id="main-content">
<!-- Content Header (Page header) --> 
<?php
}
?>
